module.exports = {
  language: 'fr-FR',
  'en-EN': {
    /* Global errors */
    missingParameters: 'Missing parameters :(',
    unexpectedBehavior: 'Unexpected behavior.',
    /* Token errors */
    tokenAuthFailed: 'Failed to authenticate token.',
    tokenExpired: 'Token is expired.',
    tokenNotFound: 'Please provide a token.',
    /* Users strings */
    userExists: 'User already exists.',
    userShowAllNotFound: 'There are no users.',
    userNotFound: "User doesn't exist.",
    userEmailExists: 'This email is already taken by another user.',
    invalidEmail: 'Email is not valid.',
    userFound: 'User found successfully.',
    userSectorsFound: 'User sectors found successfully.',
    userShowAllFound: 'Users found successfully.',
    userSaved: 'User saved successfully.',
    userRemoved: 'User removed successfully.',
    userUpdated: 'User updated successfully.',
    userAddressStored: 'User address stored successfully.',
    userAddressNotFound: 'User address not found',
    userAuthNotFound: 'Authentication failed because the user was not found.',
    userAuthFailed: 'The email address or password you entered is not valid.',
    forbidden: 'Forbidden.',
    userAuthentified: 'User authenticated successfully.',
    /* Ogust */
    OgustGetTokenOk: 'Ogust Token well retrieved.',
    OgustGetTokenFailed: 'Ogust Token retrieving failed.',
    servicesFound: 'Ogust services found.',
    servicesNotFound: 'Ogust services not found.',
    serviceFound: 'Ogust service found.',
    serviceNotFound: 'Ogust service not found.',
    serviceUpdated: 'Ogust service updated.',
    thirdPartyInfoNotFound: 'Ogust third party information not found.',
    thirdPartyInfoFound: 'Ogust third party information retrieving failed.',
    thirdPartyInfoEdited: 'Ogust third party information edited successully.',
    salariesNotFound: 'Ogust employee\'s salaries not found.',
    salariesFound: 'Ogust employee\'s found.',
    facebookGetWhitelistedDomainsOk: 'Facebook whitelisted domains found.',
    facebookPostWhitelistedDomainsOk: 'Facebook whitelisted domain(s) added.',
    facebookNoToken: 'Facebook Token not provided.',
    blogGetRssFeedsOk: 'Rss feed found.',
    blogGetRssFeedsNoUrl: 'URL not provided.',
    customerCodesEdited: 'Ogust customer codes edited successfully',
    fiscalAttestsFound: 'Customer fiscal attestations found.',
    fiscalAttestsNotFound: 'Customer fiscal attestations not found.',
    invoicesFound: 'Customer invoices found.',
    invoicesNotFound: 'Customer invoices not found.',
    bankInfoFound: 'Bank info found.',
    bankInfoUpdated: 'Bank info updated.',
    employmentContractShowAllFound: 'Employment contracts found.',
    employmentContractFound: 'Employment contract found.',
    employmentContractCreated: 'Employment contract created.',
    employmentContractSaved: 'Employment contract saved.',
    /* Messages */
    getAllMessagesFound: 'Messages found successfully.',
    getAllMessagesNotFound: 'Messages not found.',
    messageNotFound: 'Message not found.',
    storeMessage: 'Message successfully stored.',
    messageRecipientAdded: 'Message recipient added successfully.',
    /* Planning modifications */
    planningModificationsFound: 'Planning modifications found.',
    planningModificationsNotFound: 'Planning moddifications not found.',
    planningModificationStored: 'Planning modification stored successfully.',
    planningModificationUpdated: 'Planning modification updated successfully.',
    planningModificationDeleted: 'Planning modification deleted successfully.',
    /* SMS */
    smsNotSent: 'SMS not sent.',
    smsSent: 'SMS well sent.',
    smsListFound: 'SMS record list found.',
    /* Activation Code */
    activationCodeCreated: 'Activation code created.',
    activationCodeNotFoundOrInvalid: 'Activation code not found or invalid.',
    activationCodeValidated: 'Activation code validated.',
    refreshTokenNotFound: 'Refresh token not found.',
    activationCodeDeleted: 'Activation data deleted.',
    /* Role */
    roleCreated: 'Role created.',
    roleDeleted: 'Role deleted.',
    roleUpdated: 'Role updated.',
    rolesShowAllNotFound: 'Roles not found.',
    roleNotFound: 'Role not found',
    roleExists: 'Role already exists.',
    roleRemoved: 'Role removed.',
    /* Feature */
    featureCreated: 'Feature created.',
    featureDeleted: 'Feature deleted.',
    featureUpdated: 'Feature updated.',
    featuresShowAllNotFound: 'Features not found.',
    featureNotFound: 'Feature not found',
    featureExists: 'Feature already exists.',
    featuresDoNotExist: 'Features do not exist.',
    featureRemoved: 'Feature removed.',
    invalidPermLevel: 'Invalid feature permission level.',
    /* Feature */
    rightCreated: 'Right created.',
    rightDeleted: 'Right deleted.',
    rightUpdated: 'Right updated.',
    rightsShowAllNotFound: 'Rights not found.',
    rightNotFound: 'Right not found',
    rightExists: 'Right already exists.',
    rightsDoNotExist: 'Rights do not exist.',
    rightRemoved: 'Right removed.',
    /* Email */
    emailSent: 'Email successfully sent.',
    /* Reset password token */
    resetPasswordTokenFound: 'Reset password token found.',
    resetPasswordTokenNotFound: 'Reset password token not found.',
    /* ID number */
    idNumberCreated: 'ID number successfully created.',
    /* Uploader */
    fileNotFound: 'File not found.',
    fileFound: 'File found.',
    fileDeleted: 'File Deleted',
    folderCreated: 'Folder successfully created.',
    folderCreationFailure: 'Folder creation Failed.',
    fileCreated: 'File successfully created.'
  },
  'fr-FR': {
    /* Global errors */
    missingParameters: 'Paramètres manquants :(',
    unexpectedBehavior: 'Comportement inattendu.',
    /* Token errors */
    tokenAuthFailed: "Impossible d'authentifier le token.",
    tokenExpired: 'Le token a expiré.',
    tokenNotFound: 'Merci de fournir un token.',
    /* Users strings */
    userExists: "L'utilisateur existe déjà.",
    userShowAllNotFound: "Il n'y a aucun utilisateur.",
    userNotFound: "L'utilisateur n'existe pas.",
    userEmailExists: 'Cet email est déjà pris par un autre utilisateur.',
    invalidEmail: "L'email n'est pas valide.",
    userSaved: 'Utilisateur enregistré avec succès.',
    userShowAllFound: 'Utilisateurs trouvés avec succès.',
    userSectorsFound: 'Communautés trouvés avec succès.',
    userFound: 'Utilisateur trouvé avec succès.',
    userRemoved: 'Utilisateur supprimé avec succès.',
    userUpdated: 'Utilisateur modifié avec succès.',
    userAddressStored: 'Adresse utilisateur enregistré avec succès',
    userAddressNotFound: "Adresse utilisateur n'existe pas.",
    userAuthNotFound: "L'authentification a échoué car l'utilisateur n'existe pas.",
    userAuthFailed: "L'adresse email ou le mot de passe est invalide.",
    forbidden: 'Accès non autorisé.',
    userAuthentified: 'Utilisateur authentifié avec succès.',
    /* Ogust */
    OgustGetTokenOk: 'Token Ogust reçu avec succès.',
    OgustGetTokenFailed: 'Problème lors de la récupération du Token Ogust.',
    servicesFound: 'Services Ogust reçus avec succès.',
    servicesNotFound: 'Services Ogust non trouvés.',
    serviceFound: 'Service Ogust reçu avec succès.',
    serviceNotFound: 'Service Ogust non trouvé.',
    serviceUpdated: 'Service Ogust mis à jour',
    thirdPartyInfoNotFound: 'La récupération des informations tierces a échoué.',
    thirdPartyInfoFound: 'Informations tierces récupérées avec succès.',
    thirdPartyInfoEdited: 'Informations tierces éditées avec succès.',
    salariesNotFound: 'Echec lors de la récupération des bulletins de salaire de l\'employé.',
    salariesFound: 'Bulletins de salaire de l\'employé trouvés avec succès.',
    facebookGetWhitelistedDomainsOk: 'Domains whitelistés Facebook récupérés avec succès.',
    facebookPostWhitelistedDomainsOk: 'Domaine(s) whitelisté(s) ajoutés avec succès.',
    facebookNoToken: 'Merci de fournir un token d\'accès de page Facebook.',
    blogGetRssFeedsOk: 'Flux Rss trouvé avec succès.',
    blogGetRssFeedsNoUrl: 'URL manquante',
    customerCodesEdited: 'Codes bénéficiaires edités avec succès.',
    fiscalAttestsFound: 'Attestations fiscales du bénéficiaire trouvées.',
    fiscalAttestsNotFound: 'Attestations fiscales du bénéficiaire non trouvées',
    invoicesFound: 'Factures bénéficiaire trouvées.',
    invoicesNotFound: 'Factures bénéficiaire non trouvées.',
    bankInfoFound: 'Informations bancaires trouvées.',
    bankInfoUpdated: 'Informations bancaires mises à jour.',
    employmentContractShowAllFound: "Contrats d'embauche trouvés.",
    employmentContractFound: "Contrat d'embauche trouvé.",
    employmentContractCreated: "Contrat d'embauche créé.",
    employmentContractSaved: "Contrat d'embauche enregistré.",
    /* Messages */
    getAllMessagesFound: 'Messages trouvés avec succès.',
    getAllMessagesNotFound: 'Pas de messages.',
    messageNotFound: 'Message non trouvé.',
    storeMessage: 'Message enregistré avec succès.',
    messageRecipientUpdated: 'Destinataire message ajouté avec succès.',
    /* Planning modifications */
    planningModificationsFound: 'Modifications planning trouvées.',
    planningModificationsNotFound: 'Pas de modifications planning.',
    planningModificationStored: 'Modification planning enregistré avec succès.',
    planningModificationUpdated: 'Modification planning mise a jour avec succès.',
    planningModificationDeleted: 'Modification planning supprimée avec succès.',
    /* SMS */
    smsNotSent: 'SMS non envoyé.',
    smsSent: 'SMS bien envoyé.',
    smsListFound: 'Liste enregistrement SMS trouvée.',
    /* Activation Code */
    activationCodeCreated: 'Code activation créé.',
    activationCodeNotFoundOrInvalid: 'Code activation non trouvé ou invalide.',
    activationCodeValidated: 'Code activation validé.',
    refreshTokenNotFound: 'Refresh token not found.',
    activationCodeDeleted: 'Données d\'activations bien effacées.',
    /* Role */
    roleCreated: 'Rôle créé.',
    roleDeleted: 'Rôle effacé.',
    roleUpdated: 'Rôle mis à jour.',
    rolesShowAllNotFound: 'Rôles non trouvés.',
    roleNotFound: 'Role non trouvé.',
    roleExists: 'Role déjà existant.',
    roleRemoved: 'Role supprimé.',
    /* Feature */
    featureCreated: 'Feature créée.',
    featureDeleted: 'Feature effacée.',
    featureUpdated: 'Feature mise à jour.',
    featuresShowAllNotFound: 'Features non trouvées.',
    featureNotFound: 'Feature non trouvée.',
    featureExists: 'Feature déjà existante.',
    featuresDoNotExist: "Features n'existent pas.",
    featureRemoved: 'Feature supprimé.',
    invalidPermLevel: 'Permission de la feature invalide.',
    /* Email */
    emailSent: 'Email envoyé avec succès.',
    /* Reset password token */
    resetPasswordTokenFound: 'Token de changement de password trouvé.',
    resetPasswordTokenNotFound: 'Token de changement de password non trouvé.',
    /* ID number */
    idNumberCreated: 'Matricule créé.',
    /* Uploader */
    fileNotFound: 'Fichier non trouvé.',
    fileFound: 'Fichier trouvé.',
    fileDeleted: 'Fichier supprimé.',
    folderCreated: 'Dossier créé.',
    folderCreationFailure: 'La création de dossier a échouée.',
    fileCreated: 'Fichier créé.'
  }
};
