module.exports = {
  language: 'fr-FR',
  'en-EN': {
    /* Global errors */
    missingParameters: 'Missing parameters :(',
    unexpectedBehavior: 'Unexpected behavior.',
    /* Token errors */
    tokenAuthFailed: 'Failed to authenticate token.',
    tokenExpired: 'Token is expired.',
    tokenNotFound: 'Please provide a token.',
    /* Users strings */
    userExists: 'User already exists.',
    userShowAllNotFound: 'There are no users.',
    userNotFound: "User doesn't exist.",
    userEmailExists: 'This email is already taken by another user.',
    invalidEmail: 'Email is not valid.',
    userFound: 'User found successfully.',
    userSectorsFound: 'User sectors found successfully.',
    userShowAllFound: 'Users found successfully.',
    userSaved: 'User saved successfully.',
    userRemoved: 'User removed successfully.',
    userUpdated: 'User updated successfully.',
    userAddressStored: 'User address stored successfully.',
    userAddressNotFound: 'User address not found',
    userAuthNotFound: 'Authentication failed because the user was not found.',
    userAuthFailed: 'The email address or password you entered is not valid.',
    forbidden: 'Forbidden.',
    userAuthentified: 'User authenticated successfully.',
    /* Ogust */
    OgustGetTokenOk: 'Ogust Token well retrieved.',
    OgustGetTokenFailed: 'Ogust Token retrieving failed.',
    servicesFound: 'Ogust Services found.',
    servicesNotFound: 'Ogust Services not found.',
    serviceFound: 'Ogust Service found.',
    serviceNotFound: 'Ogust Service not found.',
    thirdPartyInfoNotFound: 'Ogust third party information not found.',
    thirdPartyInfoFound: 'Ogust third party information retrieving failed.',
    thirdPartyInfoEdited: 'Ogust third party information edited successully.',
    salariesNotFound: 'Ogust employee\'s salaries not found.',
    salariesFound: 'Ogust employee\'s found.',
    facebookGetWhitelistedDomainsOk: 'Facebook whitelisted domains found.',
    facebookPostWhitelistedDomainsOk: 'Facebook whitelisted domain(s) added.',
    facebookNoToken: 'Facebook Token not provided.',
    blogGetRssFeedsOk: 'Rss feed found.',
    blogGetRssFeedsNoUrl: 'URL not provided.',
    customerCodesEdited: 'Ogust customer codes edited successfully',
    /* Messages */
    getAllMessagesFound: 'Messages found successfully.',
    getAllMessagesNotFound: 'Messages not found.',
    messageNotFound: 'Message not found.',
    storeMessage: 'Message successfully stored.',
    messageRecipientAdded: 'Message recipient added successfully.',
    /* Planning modifications */
    planningModificationsFound: 'Planning modifications found.',
    planningModificationsNotFound: 'Planning moddifications not found.',
    planningModificationStored: 'Planning modification stored successfully.',
    planningModificationUpdated: 'Planning modification updated successfully.',
    planningModificationDeleted: 'Planning modification deleted successfully.',
    /* SMS */
    smsNotSent: 'SMS not sent.',
    smsSent: 'SMS well sent.',
    /* Activation Code */
    activationCodeCreated: 'Activation code created.',
    activationCodeNotFoundOrInvalid: 'Activation code not found or invalid.',
    activationCodeValidated: 'Activation code validated.',
    refreshTokenNotFound: 'Refresh token not found.',
    activationCodeDeleted: 'Activation data deleted.',
    /* Role */
    roleCreated: 'Role created.',
    roleDeleted: 'Role deleted.',
    roleUpdated: 'Role updated.',
    rolesShowAllNotFound: 'Roles not found.',
    roleNotFound: 'Role not found',
    roleExists: 'Role already exists.',
    /* Feature */
    featureCreated: 'Feature created.',
    featureDeleted: 'Feature deleted.',
    featureUpdated: 'Feature updated.',
    featuresShowAllNotFound: 'Features not found.',
    featureNotFound: 'Feature not found',
    featureExists: 'Feature already exists.'
  },
  'fr-FR': {
    /* Global errors */
    missingParameters: 'Paramètres manquants :(',
    unexpectedBehavior: 'Comportement inattendu.',
    /* Token errors */
    tokenAuthFailed: "Impossible d'authentifier le token.",
    tokenExpired: 'Le token a expiré.',
    tokenNotFound: 'Merci de fournir un token.',
    /* Users strings */
    userExists: "L'utilisateur existe déjà.",
    userShowAllNotFound: "Il n'y a aucun utilisateur.",
    userNotFound: "L'utilisateur n'existe pas.",
    userEmailExists: 'Cet email est déjà pris par un autre utilisateur.',
    invalidEmail: "L'email n'est pas valide.",
    userSaved: 'Utilisateur enregistré avec succès.',
    userShowAllFound: 'Utilisateurs trouvés avec succès.',
    userSectorsFound: 'Communautés trouvés avec succès.',
    userFound: 'Utilisateur trouvé avec succès.',
    userRemoved: 'Utilisateur supprimé avec succès.',
    userUpdated: 'Utilisateur modifié avec succès.',
    userAddressStored: 'Adresse utilisateur enregistré avec succès',
    userAddressNotFound: "Adresse utilisateur n'existe pas.",
    userAuthNotFound: "L'authentification a échoué car l'utilisateur n'existe pas.",
    userAuthFailed: "L'adresse email ou le mot de passe est invalide.",
    forbidden: 'Accès non autorisé.',
    userAuthentified: 'Utilisateur authentifié avec succès.',
    /* Ogust */
    OgustGetTokenOk: 'Token Ogust reçu avec succès.',
    OgustGetTokenFailed: 'Problème lors de la récupération du Token Ogust.',
    servicesFound: 'Services Ogust reçus avec succès.',
    servicesNotFound: 'Services Ogust non trouvés.',
    serviceFound: 'Service Ogust reçu avec succès.',
    serviceNotFound: 'Service Ogust non trouvé.',
    thirdPartyInfoNotFound: 'La récupération des informations tierces a échoué.',
    thirdPartyInfoFound: 'Informations tierces récupérées avec succès.',
    thirdPartyInfoEdited: 'Informations tierces éditées avec succès.',
    salariesNotFound: 'Echec lors de la récupération des bulletins de salaire de l\'employé.',
    salariesFound: 'Bulletins de salaire de l\'employé trouvés avec succès.',
    facebookGetWhitelistedDomainsOk: 'Domains whitelistés Facebook récupérés avec succès.',
    facebookPostWhitelistedDomainsOk: 'Domaine(s) whitelisté(s) ajoutés avec succès.',
    facebookNoToken: 'Merci de fournir un token d\'accès de page Facebook.',
    blogGetRssFeedsOk: 'Flux Rss trouvé avec succès.',
    blogGetRssFeedsNoUrl: 'URL manquante',
    customerCodesEdited: 'Codes bénéficiaires edités avec succès.',
    /* Messages */
    getAllMessagesFound: 'Messages trouvés avec succès.',
    getAllMessagesNotFound: 'Pas de messages.',
    messageNotFound: 'Message non trouvé.',
    storeMessage: 'Message enregistré avec succès.',
    messageRecipientUpdated: 'Destinataire message ajouté avec succès.',
    /* Planning modifications */
    planningModificationsFound: 'Modifications planning trouvées.',
    planningModificationsNotFound: 'Pas de modifications planning.',
    planningModificationStored: 'Modification planning enregistré avec succès.',
    planningModificationUpdated: 'Modification planning mise a jour avec succès.',
    planningModificationDeleted: 'Modification planning supprimée avec succès.',
    /* SMS */
    smsNotSent: 'SMS non envoyé.',
    smsSent: 'SMS bien envoyé.',
    /* Activation Code */
    activationCodeCreated: 'Code activation créé.',
    activationCodeNotFoundOrInvalid: 'Code activation non trouvé ou invalide.',
    activationCodeValidated: 'Code activation validé.',
    refreshTokenNotFound: 'Refresh token not found.',
    activationCodeDeleted: 'Données d\'activations bien effacées.',
    /* Role */
    roleCreated: 'Rôle créé.',
    roleDeleted: 'Rôle effacé.',
    roleUpdated: 'Rôle mis à jour.',
    rolesShowAllNotFound: 'Rôles non trouvés.',
    roleNotFound: 'Role non trouvé.',
    roleExists: 'Role déjà existant.',
    /* Feature */
    featureCreated: 'Feature créée.',
    featureDeleted: 'Feature effacée.',
    featureUpdated: 'Feature mise à jour.',
    featuresShowAllNotFound: 'Features non trouvées.',
    featureNotFound: 'Feature non trouvée.',
    featureExists: 'Feature déjà existante.'
  }
};
