module.exports = {
  language: 'fr-FR',
  'en-EN': {
    /* Global errors */
    unexpectedBehavior: 'Unexpected behavior.',
    /* Token errors */
    tokenAuthFailed: 'Failed to authenticate token.',
    tokenExpired: 'Token is expired.',
    tokenNotFound: 'Please provide a token.',
    /* Users strings */
    userExists: 'User already exists.',
    usersNotFound: 'There are no users.',
    userNotFound: 'User doesn\'t exist.',
    userEmailExists: 'This email is already taken by another user.',
    invalidEmail: 'Email is not valid.',
    userFound: 'User found successfully.',
    usersFound: 'Users found successfully.',
    userSaved: 'User saved successfully.',
    userRemoved: 'User removed successfully.',
    userUpdated: 'User updated successfully.',
    userAddressStored: 'User address stored successfully.',
    userAddressNotFound: 'User address not found.',
    userAuthNotFound: 'Authentication failed because the user was not found.',
    userAuthFailed: 'The email address or password you entered is not valid.',
    forbidden: 'Forbidden.',
    userAuthentified: 'User authenticated successfully.',
    userPayDocumentDeleted: 'User pay document deleted successfully.',
    userPayDocumentNotFound: 'User pay document not found.',
    userRoleConflict: 'User already has a role on this interface',
    /* Rss feeds */
    blogGetRssFeedsOk: 'Rss feed found.',
    /* Api */
    apiVersionUpToDate: 'api version up to date',
    apiVersionToUpdate: 'api version must be updated',
    /* Messages */
    getAllMessagesFound: 'Messages found successfully.',
    getAllMessagesNotFound: 'Messages not found.',
    messageNotFound: 'Message not found.',
    storeMessage: 'Message successfully stored.',
    messageRecipientAdded: 'Message recipient added successfully.',
    /* SMS */
    smsNotSent: 'SMS not sent.',
    smsSent: 'SMS well sent.',
    smsFound: 'SMS found.',
    /* Role */
    rolesNotFound: 'Roles not found.',
    rolesFound: 'Roles found.',
    unknownRole: 'Role does not exist',
    /* Email */
    emailSent: 'Email successfully sent.',
    /* Reset password token */
    resetPasswordTokenFound: 'Reset password token found.',
    resetPasswordTokenNotFound: 'Reset password token not found.',
    /* Uploader */
    fileNotFound: 'File not found.',
    filesNotFound: 'Files not found.',
    fileFound: 'File found.',
    filesFound: 'Files found.',
    fileDeleted: 'File Deleted.',
    folderCreated: 'Folder successfully created.',
    folderCreationFailure: 'Folder creation Failed.',
    fileCreated: 'File successfully created.',
    uploadNotAllowed: 'Upload not allowed.',
    /* Company */
    companyCreated: 'Company created.',
    companyNotFound: 'Company not found.',
    companyExists: 'Company already exists.',
    companyInternalHourCreated: 'Company internal hour created',
    companyInternalHourNotFound: 'Company internal hour not found.',
    companyInternalHourUpdated: 'Company internal hour updated.',
    companyInternalHoursNotFound: 'Company internal hours not found.',
    companyInternalHoursFound: 'Company internal hours found.',
    companyInternalHourRemoved: 'Company internal hour removed.',
    companyInternalHourCreationNotAllowed: 'Company internal hour creation not allowed.',
    companyInternalHourDeletionNotAllowed: 'Company internal hour deletion not allowed.',
    companyFirstInterventionFound: 'Company first intervention found.',
    companyFirstInterventionNotFound: 'Company first intervention not found.',
    administrativeDocumentNotFound: 'Administrative document not found.',
    administrativeDocumentFound: 'Administrative documents found.',
    administrativeDocumentCreated: 'Administrative documents found.',
    administrativeDocumentRemoved: 'Administrative documents removed.',
    /* Contracts */
    contractsFound: 'Contracts found.',
    contractsNotFound: 'Contracts not found.',
    contractUpdated: 'Contract updated.',
    contractAdded: 'Contract added.',
    contractRemoved: 'Contract removed.',
    staffRegisteredFound: 'Staff Registered Found.',
    /* Contracts amendments */
    contractVersionAdded: 'Contract amendment added.',
    contractVersionRemoved: 'Contract amendment removed.',
    contractVersionUpdated: 'Contract amendment updated.',
    /* Customers */
    customersFound: 'Customers found.',
    customerFound: 'Customer found.',
    customersNotFound: 'Customers not found.',
    customerNotFound: 'Customer not found.',
    customerCreated: 'Customer created.',
    customerUpdated: 'Customer updated.',
    customerRemoved: 'Customer removed.',
    customerHelperDeleted: 'Customer helper deleted.',
    customerSubscriptionsFound: 'Customer subscriptions found.',
    customerSubscriptionsNotFound: 'Customer subscriptions not found.',
    customerSubscriptionAdded: 'Customer subscription added.',
    customerSubscriptionUpdated: 'Customer subscription updated.',
    customerSubscriptionRemoved: 'Customer subscription removed.',
    customerSubscriptionDeletionForbidden: 'Customer subscription deletion forbidden.',
    serviceAlreadySubscribed: 'Service already subscribed.',
    customerMandateUpdated: 'Customer mandate updated.',
    customerMandatesFound: 'Customer mandates found.',
    customerMandateNotFound: 'Customer mandate not found.',
    customerQuotesFound: 'Customer quotes found.',
    customerQuoteAdded: 'Customer quote added.',
    customerQuoteRemoved: 'Customer quote removed.',
    signedDocumentSaved: 'Signed document saved.',
    customerSubscriptionHistoryAdded: 'Customer subscription history added.',
    customerFundingConflict: 'Subscription is already used by another funding.',
    customerFundingNotFound: 'Customer funding not found.',
    customerFundingCreated: 'Customer funding created.',
    customerFundingUpdated: 'Customer funding updated.',
    customerFundingsFound: 'Customer fundings found.',
    customerFundingRemoved: 'Customer funding removed.',
    /* ESign */
    signatureRequestCreated: 'Signature request created.',
    documentNotFound: 'Eversign document not found.',
    documentFound: 'Eversign document found.',
    /* Google drive */
    googleDriveFolderCreationFailed: 'Google drive folder creation failed.',
    googleDriveFolderNotFound: 'Google drive folder not found.',
    googleDriveFileNotFound: 'Google drive file not found.',
    /* Events */
    eventsNotFound: 'Events not found.',
    eventNotFound: 'Event not found.',
    eventsFound: 'Events found.',
    eventCreated: 'Event created.',
    eventUpdated: 'Event updated.',
    eventDeleted: 'Event deleted.',
    eventsDeleted: 'Events deleted.',
    eventDatesNotOnSameDay: 'Start and end dates should be on the same day.',
    eventsConflict: 'Events in conflict',
    /* Sectors */
    sectorCreated: 'Sector created.',
    sectorUpdated: 'Sector updated.',
    sectorNotFound: 'Sector not found.',
    sectorsFound: 'Sectors found.',
    sectorDeleted: 'Sector deleted.',
    sectorAlreadyExists: 'Sector already exists',
    /* Services */
    servicesFound: 'Services found.',
    serviceCreated: 'Service created.',
    serviceDeleted: 'Service deleted.',
    servicesNotFound: 'Services not found.',
    serviceNotFound: 'Service not found.',
    servicesUpdated: 'Services updated.',
    /* Surcharges */
    surchargesFound: 'Surcharges found.',
    surchargeCreated: 'Surcharge created.',
    surchargeDeleted: 'Surcharge deleted.',
    surchargesNotFound: 'Surcharges not found.',
    surchargeNotFound: 'Surcharge not found.',
    surchargesUpdated: 'Surcharges updated.',
    /* Third party payers */
    thirdPartyPayerCreated: 'Company third party payer created.',
    thirdPartyPayersFound: 'Company third party payers found.',
    thirdPartyPayersNotFound: 'Company third party payers not found.',
    thirdPartyPayerUpdated: 'Company third party payer updated.',
    thirdPartyPayerDeleted: 'Company third party payer deleted.',
    /* Bills */
    billsCreated: 'Bills created.',
    draftBillsCreated: 'Draft bills created.',
    billsFound: 'Bills found.',
    billsNotFound: 'Bills not found.',
    billNotCompani: 'Bill\'s origin must be \'Compani\'.',
    /* Credit Notes */
    creditNotesFound: 'Credit notes found.',
    creditNoteCreated: 'Credit note found.',
    creditNoteDeleted: 'Credit note deleted.',
    creditNotesNotFound: 'Credit notes not found.',
    creditNoteNotFound: 'Credit note not found.',
    creditNoteUpdated: 'Credit note updated.',
    creditNoteNotCompani: 'Credit note\'s origin must be \'Compani\'.',
    /* Balances */
    balancesFound: 'Balances found.',
    /* Payments */
    paymentsFound: 'Payments found.',
    paymentsNotFound: 'Payments not found.',
    paymentNotFound: 'Payment not found.',
    paymentCreated: 'Payment created.',
    paymentUpated: 'Payment updated.',
    /* Pay */
    payListCreated: 'Pay list created.',
    hoursToWorkFound: 'Hours to work found.',
    /* Final pay */
    finalPayListCreated: 'Final pay list created.',
    /* Event history */
    eventHistoriesFound: 'Event histories found.',
    /* Pay documents */
    payDocumentCreated: 'Pay document created.',
    payDocumentsFound: 'Pay documents found.',
    payDocumentsNotFound: 'Pay documents not found.',
    payDocumentNotFound: 'Pay document not found.',
    payDocumentDeleted: 'Pay document deleted.',
    /* Stats */
    statsFound: 'Stats found.',
    statsNotFound: 'Stats not found.',
    /* Sector history */
    sectorHistoryNotFound: 'Sector history not found.',
    /* Bill slip */
    billSlipsFound: 'Bill slips found.',
    /* Tax certificates */
    taxCertificatesNotFound: 'Tax certificates not found.',
    taxCertificateNotFound: 'Tax certificate not found.',
    taxCertificatesFound: 'Tax certificates found.',
    taxCertificateCreated: 'Tax certificate created.',
    /* Establishments */
    establishmentCreated: 'Establishment created.',
    establishmentNotFound: 'Establishment not found.',
    establishmentsFound: 'Establishments found.',
    establishmentRemoved: 'Establishment removed.',
    siretAlreadyExists: 'Siret already used by another establishment.',
    /* Programs */
    programsFound: 'Programs found.',
    programsNotFound: 'Programs not found.',
    programCreated: 'Program created.',
    programFound: 'Program found.',
    programUpdated: 'Program updated.',
    /* SubPrograms */
    subProgramUpdated: 'Sub-program updated.',
    /* Steps */
    stepUpdated: 'Step updated.',
    /* Activities */
    activityFound: 'Activity found.',
    activityUpdated: 'Activity updated.',
    activityDetached: 'Activity detached.',
    /* Cards */
    cardUpdated: 'Card updated.',
    cardDeleted: 'Card deleted.',
    /* Courses */
    coursesFound: 'Courses found.',
    courseHistoriesFound: 'Course histories found.',
    coursesNotFound: 'Courses not found.',
    courseHistoriesNotFound: 'Course histories not found.',
    courseCreated: 'Course created.',
    courseFound: 'Course found.',
    courseUpdated: 'Course updated.',
    courseDeleted: 'Course deleted.',
    courseTraineeAdded: 'Course trainee added.',
    courseTraineeRemoved: 'Course trainee removed.',
    courseTraineeAlreadyExists: 'Course trainee already added to course.',
    courseTraineeNotFromCourseCompany: 'Course trainee not connected to course company',
    /* Course slots */
    courseSlotCreated: 'Course slot created.',
    courseSlotUpdated: 'Course slot updated.',
    courseSlotDeleted: 'Course slot deleted.',
    courseSlotNotFound: 'Course slot not found.',
    courseSlotConflict: 'Course slot in conflict.',
    /* Activities */
    activityHistoryCreated: 'Activity history created.',
    activityHistoryFound: 'Activity history found.',
  },
  'fr-FR': {
    /* Global errors */
    unexpectedBehavior: 'Comportement inattendu.',
    /* Token errors */
    tokenAuthFailed: 'Impossible d\'authentifier le token.',
    tokenExpired: 'Le token a expiré.',
    tokenNotFound: 'Merci de fournir un token.',
    /* Users strings */
    userExists: 'L\'utilisateur existe déjà.',
    usersNotFound: 'Il n\'y a aucun utilisateur.',
    userNotFound: 'L\'utilisateur n\'existe pas.',
    userEmailExists: 'Cet email est déjà pris par un autre utilisateur.',
    invalidEmail: 'L\'email n\'est pas valide.',
    userSaved: 'Utilisateur enregistré avec succès.',
    usersFound: 'Utilisateurs trouvés avec succès.',
    userFound: 'Utilisateur trouvé avec succès.',
    userRemoved: 'Utilisateur supprimé avec succès.',
    userUpdated: 'Utilisateur modifié avec succès.',
    userAddressStored: 'Adresse utilisateur enregistré avec succès',
    userAddressNotFound: 'Adresse utilisateur n\'existe pas.',
    userAuthNotFound: 'L\'authentification a échoué car l\'utilisateur n\'existe pas.',
    userAuthFailed: 'L\'adresse email ou le mot de passe est invalide.',
    forbidden: 'Accès non autorisé.',
    userAuthentified: 'Utilisateur authentifié avec succès.',
    userPayDocumentDeleted: 'Document de paye d\'utilisateur supprimé avec succès.',
    userPayDocumentNotFound: 'Document de paye d\'utilisateur non trouvé.',
    userRoleConflict: 'L\'utilisateur a déjà un role sur cette interface',
    /* Rss feeds */
    blogGetRssFeedsOk: 'Flux Rss trouvé avec succès.',
    /* Api */
    apiVersionUpToDate: 'La version de l\'api est à jour',
    apiVersionToUpdate: 'La version de l\'api doit être mis à jour',
    /* Messages */
    getAllMessagesFound: 'Messages trouvés avec succès.',
    getAllMessagesNotFound: 'Pas de messages.',
    messageNotFound: 'Message non trouvé.',
    storeMessage: 'Message enregistré avec succès.',
    messageRecipientUpdated: 'Destinataire message ajouté avec succès.',
    /* SMS */
    smsNotSent: 'SMS non envoyé.',
    smsSent: 'SMS bien envoyé.',
    smsFound: 'SMS trouvés.',
    /* Role */
    rolesNotFound: 'Rôles non trouvés.',
    rolesFound: 'Rôles trouvés.',
    unknownRole: 'Le rôle n\'existe pas',
    /* Email */
    emailSent: 'Email envoyé avec succès.',
    /* Reset password token */
    resetPasswordTokenFound: 'Token de changement de password trouvé.',
    resetPasswordTokenNotFound: 'Token de changement de password non trouvé.',
    /* Uploader */
    fileNotFound: 'Fichier non trouvé.',
    fileFound: 'Fichier trouvé.',
    fileDeleted: 'Fichier supprimé.',
    folderCreated: 'Dossier créé.',
    folderCreationFailure: 'La création de dossier a échouée.',
    fileCreated: 'Fichier créé.',
    uploadNotAllowed: 'Téléchargement non autorisé.',
    /* Company */
    companyCreated: 'Entreprise créée.',
    companyNotFound: 'Entreprise non trouvée.',
    companyExists: 'Entreprise déjà existante.',
    companyInternalHourCreated: 'Heure interne de l\'entreprise créée.',
    companyInternalHourNotFound: 'Heure interne de l\'entreprise non trouvée.',
    companyInternalHourUpdated: 'Heure interne de l\'entreprise modifiée.',
    companyInternalHoursNotFound: 'Heures internes de l\'entreprise non trouvées.',
    companyInternalHoursFound: 'Heures internes de l\'entreprise trouvées.',
    companyInternalHourRemoved: 'Heure interne de l\'entreprise supprimé.',
    companyInternalHourCreationNotAllowed: 'Creation de l\'heure interne non autorisée.',
    companyInternalHourDeletionNotAllowed: 'Suppression de l\'heure interne non autorisée.',
    companyFirstInterventionFound: 'Première intervention de l\'entreprise trouvée.',
    companyFirstInterventionNotFound: 'Première intervention de l\'entreprise non trouvée.',
    administrativeDocumentNotFound: 'Document administratif non trouvé.',
    administrativeDocumentFound: 'Document administratif trouvé.',
    administrativeDocumentCreated: 'Document administratif créé.',
    administrativeDocumentRemoved: 'Document administratif supprimé.',
    /* Contracts */
    contractsFound: 'Contrats trouvés.',
    contractsNotFound: 'Contrats non trouvés.',
    contractUpdated: 'Contrat mis à jour.',
    contractAdded: 'Contrat ajouté.',
    contractRemoved: 'Contrat supprimé.',
    staffRegisteredFound: 'Registre Unique du personnel récuperé.',
    /* Contracts amendments */
    contractVersionAdded: 'Avenant au contrat ajouté.',
    contractVersionRemoved: 'Avenant au contrat supprimé.',
    contractVersionUpdated: 'Avenant au contrat modifié.',
    /* Customers */
    customersFound: 'Bénéficiaires trouvés.',
    customerFound: 'Bénéficiaire trouvé.',
    customersNotFound: 'Bénéficiaires non trouvés.',
    customerNotFound: 'Bénéficiaire non trouvé.',
    customerCreated: 'Bénéficiaire créé.',
    customerUpdated: 'Bénéficiaire mis à jour.',
    customerRemoved: 'Bénéficiaire supprimé',
    customerHelperDeleted: 'Aidant du bénéficiaire supprimé.',
    customerSubscriptionsFound: 'Abonnements du bénéficiaire trouvés',
    customerSubscriptionsNotFound: 'Abonnements du bénéficiaire non trouvés',
    customerSubscriptionAdded: 'Abonnement du bénéficiaire ajouté.',
    customerSubscriptionUpdated: 'Abonnement du bénéficiaire mis à jour.',
    customerSubscriptionRemoved: 'Abonnement du bénéficiaire supprimé.',
    customerSubscriptionDeletionForbidden: 'Impossible de supprimer l\'abonnement du bénéficiaire.',
    serviceAlreadySubscribed: 'Le bénéficiaire est déjà abonné à ce service',
    customerMandateUpdated: 'Mandat du bénéficiaire mis à jour',
    customerMandatesFound: 'Mandats du bénéficiaire trouvés',
    customerMandateNotFound: 'Mandat du bénéficiaire non trouvé',
    customerQuotesFound: 'Devis du bénéficiaire trouvés.',
    customerQuoteAdded: 'Devis du bénéficiaire ajouté.',
    customerQuoteRemoved: 'Devis du bénéficiaire supprimé.',
    signedDocumentSaved: 'Document signé enregistré.',
    customerSubscriptionHistoryAdded: 'Historique de l\'abonnement du bénéficiaire ajouté.',
    customerFundingConflict: 'Le service est déjà utilisé par un autre financement.',
    customerFundingNotFound: 'Financement du bénéficiaire non trouvé.',
    customerFundingCreated: 'Financement du bénéficiaire créé.',
    customerFundingUpdated: 'Financement du bénéficiaire modifié.',
    customerFundingsFound: 'Financements du bénéficiaire trouvés.',
    customerFundingRemoved: 'Financement du bénéficiaire supprimé.',
    /* ESign */
    signatureRequestCreated: 'Demande de signature créée.',
    documentNotFound: 'Document eversign non trouvé.',
    documentFound: 'Document eversign trouvé.',
    /* Google drive */
    googleDriveFolderCreationFailed: 'Echec de la création du dossier google drive.',
    googleDriveFolderNotFound: 'Dossier google drive non trouvé.',
    googleDriveFileNotFound: 'Fichier google drive non trouvé.',
    /* Events */
    eventsNotFound: 'Evènements non trouvés.',
    eventNotFound: 'Evènement non trouvé.',
    eventsFound: 'Evènement trouvé.',
    eventCreated: 'Evènement crée.',
    eventUpdated: 'Evènement mis à jour.',
    eventDeleted: 'Evènement supprimé.',
    eventsDeleted: 'Evènements supprimé.',
    eventDatesNotOnSameDay: 'Les dates de début et de fin devraient être le même jour.',
    eventsConflict: 'Evènement en conflit avec les évènements de l\'auxiliaire.',
    /* Sectors */
    sectorCreated: 'Équipe créée.',
    sectorUpdated: 'Équipe modifiée.',
    sectorNotFound: 'Équipe non trouvée.',
    sectorsFound: 'Équipes trouvées.',
    sectorDeleted: 'Équipe supprimée.',
    sectorAlreadyExists: 'Équipe déjà existante',
    /* Services */
    servicesFound: 'Services trouvés.',
    serviceCreated: 'Service créé.',
    serviceDeleted: 'Service supprimé.',
    servicesNotFound: 'Services non trouvés.',
    serviceNotFound: 'Service non trouvé.',
    servicesUpdated: 'Service modifié.',
    /* Surcharges */
    surchargesFound: 'Plans de majorations trouvés.',
    surchargeCreated: 'Plan de majoration créé.',
    surchargeDeleted: 'Plan de majoration supprimé.',
    surchargesNotFound: 'Plans de majorations non trouvés.',
    surchargeNotFound: 'Plan de majoration non trouvé.',
    surchargeUpdated: 'Plan de majoration modifié.',
    /* Third party payers */
    thirdPartyPayerCreated: 'Tiers payeur de l\'entreprise créé.',
    thirdPartyPayersFound: 'Tiers payeurs de l\'entreprise trouvés.',
    thirdPartyPayersNotFound: 'Tiers payeurs de l\'entreprise non trouvés.',
    thirdPartyPayerUpdated: 'Tiers payeur de l\'entreprise modifié.',
    thirdPartyPayerDeleted: 'Tiers payeur de l\'entreprise supprimé.',
    /* Bills */
    billsCreated: 'Factures crées.',
    draftBillsCreated: 'Brouillons de facture générés.',
    billsFound: 'Factures trouvés.',
    billsNotFound: 'Factures non trouvés.',
    billNotCompani: 'L\'origine de la facture doit être \'Compani\'.',
    /* Credit Notes */
    creditNotesFound: 'Avoirs trouvés.',
    creditNoteCreated: 'Avoir créé.',
    creditNoteDeleted: 'Avoir supprimé.',
    creditNotesNotFound: 'Avoirs non trouvés.',
    creditNoteNotFound: 'Avoir non trouvé.',
    creditNoteUpdated: 'Avoir modifié.',
    creditNoteNotCompani: 'L\'origine de l\'avoir doit être \'Compani\'.',
    /* Balances */
    balancesFound: 'Balances trouvées.',
    /* Payments */
    paymentsFound: 'Règlements trouvés.',
    paymentsNotFound: 'Règlements non trouvés.',
    paymentCreated: 'Règlement créé.',
    paymentNotFound: 'Règlement non trouvé.',
    paymentUpated: 'Règlement modifié.',
    /* Pay */
    payListCreated: 'Liste de paie créée',
    hoursToWorkFound: 'Heures à travailler trouvées.',
    /* Final pay */
    finalPayListCreated: 'Liste des stc créée.',
    /* Event history */
    eventHistoriesFound: 'Historique des évènements trouvés.',
    /* Pay documents */
    payDocumentCreated: 'Document de paie créé.',
    payDocumentsFound: 'Documents de paie trouvés.',
    payDocumentsNotFound: 'Documents de paie non trouvés.',
    payDocumentNotFound: 'Document de paie non trouvé.',
    payDocumentDeleted: 'Document de paie supprimé.',
    /* Stats */
    statsFound: 'Statistiques trouvées.',
    statsNotFound: 'Statistiques non trouvées.',
    /* Sector history */
    sectorHistoryNotFound: 'Historique du secteur non trouvé.',
    /* Bill slip */
    billSlipsFound: 'Bordereaux trouvés.',
    /* Tax certificates */
    taxCertificatesNotFound: 'Attestations fiscales non trouvées.',
    taxCertificateNotFound: 'Attestation fiscale non trouvée.',
    taxCertificatesFound: 'Attestations fiscales trouvées.',
    taxCertificateCreated: 'Attestation fiscale créée.',
    /* Establishments */
    establishmentCreated: 'Établissement créé.',
    establishmentNotFound: 'Établissement non trouvé.',
    establishmentsFound: 'Établissements trouvés.',
    establishmentRemoved: 'Établissement supprimé.',
    siretAlreadyExists: 'Siret déjà utilisé par un autre établissement.',
    /* Programs */
    programsFound: 'Liste des programmes trouvés.',
    programsNotFound: 'Liste des programmes non trouvés.',
    programCreated: 'Programme créé.',
    programFound: 'Programme trouvé.',
    programUpdated: 'Programme mis à jour.',
    /* SubPrograms */
    subProgramUpdated: 'Sous-Programme mis à jour.',
    /* Steps */
    stepUpdated: 'Étape mise à jour.',
    /* Activities */
    activityFound: 'Activité trouvée.',
    activityUpdated: 'Activité mise à jour.',
    activityDetached: 'Activité retirée.',
    /* Cards */
    cardUpdated: 'Carte mise à jour',
    cardDeleted: 'Carte supprimée',
    /* Courses */
    coursesFound: 'Liste des formations trouvée.',
    courseHistoriesFound: 'Liste des historiques de formation trouvée.',
    coursesNotFound: 'Liste des formations non trouvée.',
    courseHistoriesNotFound: 'Liste des historiques de formation non trouvée.',
    courseCreated: 'Formation créée.',
    courseFound: 'Formation trouvée.',
    courseUpdated: 'Formation mise à jour.',
    courseDeleted: 'Formation supprimée.',
    courseTraineeAdded: 'Stagiaire ajouté à la formation.',
    courseTraineeRemoved: 'Stagiaire supprimé de la formation.',
    courseTraineeAlreadyExists: 'Stagiaire déjà ajouté à la formation.',
    courseTraineeNotFromCourseCompany: 'Ce stagiaire n\'est pas relié à la structure de la formation',
    /* Course slots */
    courseSlotCreated: 'Créneau de formation créé.',
    courseSlotUpdated: 'Créneau de formation mis à jour.',
    courseSlotDeleted: 'Créneau de formation supprimé.',
    courseSlotNotFound: 'Créneau de formation non trouvé.',
    courseSlotConflict: 'Créneau de formation en conflit.',
    /* Activities */
    activityHistoryCreated: 'Historique d\'activité créé.',
    activityHistoryFound: 'Historique d\'activité trouvé.',
  },
};
