const Joi = require('joi');

const surchargedHoursValidation = Joi.object().keys({
  hours: Joi.number().required(),
  percentage: Joi.number().required().min(0).max(100),
});

const surchargedDetailsValidation = Joi.object().required().pattern(Joi.string(), {
  planName: Joi.string().required(),
  saturday: surchargedHoursValidation,
  sunday: surchargedHoursValidation,
  publicHoliday: surchargedHoursValidation,
  twentyFifthOfDecember: surchargedHoursValidation,
  firstOfMay: surchargedHoursValidation,
  firstOfJanuary: surchargedHoursValidation,
  evening: surchargedHoursValidation,
  custom: surchargedHoursValidation,
});

exports.payValidation = {
  absencesHours: Joi.number().required(),
  additionalHours: Joi.number().required(),
  auxiliary: Joi.objectId().required(),
  bonus: Joi.number().required(),
  contractHours: Joi.number().required(),
  diff: Joi.object().keys({
    absencesHours: Joi.number().required(),
    hoursBalance: Joi.number().required(),
    internalHours: Joi.number().required(),
    notSurchargedAndExempt: Joi.number().required(),
    notSurchargedAndNotExempt: Joi.number().required(),
    paidTransportHours: Joi.number().required(),
    surchargedAndExempt: Joi.number().required(),
    surchargedAndExemptDetails: surchargedDetailsValidation.required(),
    surchargedAndNotExempt: Joi.number().required(),
    surchargedAndNotExemptDetails: surchargedDetailsValidation.required(),
    workedHours: Joi.number().required(),
  }),
  endDate: Joi.date().required(),
  holidaysHours: Joi.number().required(),
  hoursBalance: Joi.number().required(),
  hoursCounter: Joi.number().required(),
  hoursToWork: Joi.number().required(),
  internalHours: Joi.number().required(),
  month: Joi.string().required(),
  mutual: Joi.boolean().required(),
  notSurchargedAndExempt: Joi.number().required(),
  notSurchargedAndNotExempt: Joi.number().required(),
  phoneFees: Joi.number().required(),
  overtimeHours: Joi.number().required(),
  paidTransportHours: Joi.number().required(),
  previousMonthHoursCounter: Joi.number().required(),
  startDate: Joi.date().required(),
  surchargedAndExempt: Joi.number().required(),
  surchargedAndExemptDetails: surchargedDetailsValidation,
  surchargedAndNotExempt: Joi.number().required(),
  surchargedAndNotExemptDetails: surchargedDetailsValidation,
  transport: Joi.number().required(),
  travelledKm: Joi.number().required(),
  workedHours: Joi.number().required(),
};
